name: 'Set Commit Status'
description: 'Set a GitHub commit status for the current repo & commit.'
inputs:
  context:
    description: 'A string label to differentiate this status from the status of other systems. This field is case-insensitive.'
    required: true
  description:
    description: 'Optional short description of the commit status.'
    required: false
  state:
    description: 'The state of the commit status. Must be one of `error`, `failure`, `pending`, or `success`. (Default is `success`)'
    required: true
    default: 'success'
  target-url:
    description: 'Optional target URL to associate with the status.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set the status
      uses: actions/github-script@v6
      env:
        DESCRIPTION: ${{ inputs.description }}
        TARGET_URL: ${{ inputs.target-url }}
      with:
        script: |
          { DESCRIPTION, TARGET_URL } = process.env
          await github.rest.createCommitStatus({
            context: "${{ inputs.context }}",
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: "${{ inputs.state }}",
            ...DESCRIPTION && { description: DESCRIPTION },
            ...TARGET_URL && { target_url: TARGET_URL }", 
          })
